/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.conexion;
import javax.swing.JOptionPane;
/**
 *
 * @author Jairo de León
 */
public class login extends javax.swing.JFrame {
    
    public static String user = "";
    String pass = "";
    
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setSize(400,550);
        setResizable(false);
        setTitle("Acceso al sistema");
        setLocationRelativeTo(null);
        
        ImageIcon wallpaper = new ImageIcon("src/image/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_wallpaper.getWidth(),
                jLabel_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();
        
        ImageIcon wallpaper_logo = new ImageIcon("src/image/logo.png");
        Icon icono_logo = new ImageIcon(wallpaper_logo.getImage().getScaledInstance(jLabel1_Logo.getWidth(),
                jLabel1_Logo.getHeight(), Image.SCALE_DEFAULT));
        jLabel1_Logo.setIcon(icono_logo);
        this.repaint();
        
    }
    
    @Override
    public Image getIconImage(){
           Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("image/icon.png"));
           return retValue; 
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_user = new javax.swing.JTextField();
        jLabel1_Logo = new javax.swing.JLabel();
        jButton1_acceder = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_user.setBackground(new java.awt.Color(153, 153, 255));
        txt_user.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_user.setForeground(new java.awt.Color(255, 255, 255));
        txt_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 330, 210, -1));
        getContentPane().add(jLabel1_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 11, 217, 189));

        jButton1_acceder.setBackground(new java.awt.Color(153, 153, 255));
        jButton1_acceder.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1_acceder.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_acceder.setText("Acceder");
        jButton1_acceder.setBorder(null);
        jButton1_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_accederActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 416, 209, -1));

        txt_password.setBackground(new java.awt.Color(153, 153, 255));
        txt_password.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 370, 210, -1));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_accederActionPerformed
        user = txt_user.getText().trim();
        pass = txt_password.getText().trim();
        
        if(!user.equals("") || !pass.equals("")){
            
            try {
                Connection cn = conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                    "select tipousuario, status from usuario where nombreusuario ='" +user
                            +"' and contrasena = '"+pass +"'");
                
                ResultSet rs = pst.executeQuery();
                if(rs.next()){
                
                    String tipousuario = rs.getString("tipousuario");
                    String status = rs.getString("status");
                    
                    if(tipousuario.equalsIgnoreCase("administrador") && status.equalsIgnoreCase("activo")){
                        dispose();
                        new administrador().setVisible(true);
                    
                    } else if(tipousuario.equalsIgnoreCase("usuariosistema") && status.equalsIgnoreCase("activo")){
                      dispose();
                      new usuariosistema().setVisible(true);
                      dispose();
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Datos de acceso incorrectos");
                    txt_user.setText("");
                    txt_password.setText("");
                }
                
            } catch (Exception e) {
                System.err.println("Error en el botón acceder"+e);
                JOptionPane.showMessageDialog(null, "¡¡Error al iniciar sesión, contacte al administrador.!!");
            }
        
        }else{
            JOptionPane.showMessageDialog(null, "Debe de llenar los campos!");
        }
         
    }//GEN-LAST:event_jButton1_accederActionPerformed

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_acceder;
    private javax.swing.JLabel jLabel1_Logo;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
